// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs3-7EqzW92C5a4qBIog26CKxsFg0rCUs',
    appId: '1:644084403539:web:bbb500f6dbe7369a8de5a6',
    messagingSenderId: '644084403539',
    projectId: 'chat-app-54b3c',
    authDomain: 'chat-app-54b3c.firebaseapp.com',
    storageBucket: 'chat-app-54b3c.appspot.com',
    measurementId: 'G-Y2RHG5JGJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASNLkrPMhO67H-V3SmXbFgplm3NRzvQrc',
    appId: '1:644084403539:android:30a703a8997857268de5a6',
    messagingSenderId: '644084403539',
    projectId: 'chat-app-54b3c',
    storageBucket: 'chat-app-54b3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdRBF20v7tvPN_MDik2LTmCZ4Z4xE-rIg',
    appId: '1:644084403539:ios:dfd237d45c4b53288de5a6',
    messagingSenderId: '644084403539',
    projectId: 'chat-app-54b3c',
    storageBucket: 'chat-app-54b3c.appspot.com',
    iosClientId: '644084403539-cu3iiqpfes2589d9glt579t2njog8c4j.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.chatapp',
  );
}
